#!/usr/bin/env python3
"""Import an All API Hub backup into api_hub_signin config.

The importer is intentionally conservative. It only imports enabled, healthy,
auto-check-in New API accounts that authenticate with access_token and do not
use custom external check-in URLs.

Secrets are written to the env file. The JSON config only references env names.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shlex
from pathlib import Path
from typing import Any


def load_backup(path: str) -> list[dict[str, Any]]:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    accounts = data.get("accounts", {}).get("accounts", [])
    if not isinstance(accounts, list):
        raise SystemExit("invalid backup: accounts.accounts is not a list")
    return accounts


def get_checkin(account: dict[str, Any]) -> dict[str, Any]:
    value = account.get("checkIn") or {}
    return value if isinstance(value, dict) else {}


def custom_url(account: dict[str, Any]) -> str:
    custom = get_checkin(account).get("customCheckIn") or {}
    return str(custom.get("url") or "")


def should_import(account: dict[str, Any]) -> tuple[bool, list[str]]:
    reasons: list[str] = []
    info = account.get("account_info") or {}
    health = account.get("health") or {}
    checkin = get_checkin(account)

    if account.get("disabled"):
        reasons.append("disabled")
    if checkin.get("autoCheckInEnabled") is not True:
        reasons.append("auto_checkin_off")
    if health.get("status") != "healthy":
        reasons.append("unhealthy")
    if account.get("site_type") != "new-api":
        reasons.append("unsupported_site_type")
    if account.get("authType") != "access_token":
        reasons.append("unsupported_auth_type")
    if not info.get("access_token"):
        reasons.append("missing_access_token")
    if custom_url(account):
        reasons.append("custom_checkin_url")
    return not reasons, reasons


def env_name_for(account: dict[str, Any]) -> str:
    raw = f"{account.get('id', '')}|{account.get('site_url', '')}"
    digest = hashlib.sha1(raw.encode("utf-8")).hexdigest()[:12].upper()
    return f"API_HUB_TOKEN_{digest}"


def safe_name(value: str) -> str:
    return re.sub(r"[\r\n\t]+", " ", value).strip() or "unnamed"


def build_outputs(accounts: list[dict[str, Any]]) -> tuple[dict[str, Any], list[str], dict[str, Any]]:
    config_accounts: list[dict[str, Any]] = []
    env_lines = ["# Generated by import_all_api_hub_backup.py. Keep this file private."]
    imported: list[dict[str, Any]] = []
    skipped: list[dict[str, Any]] = []

    for account in accounts:
        ok, reasons = should_import(account)
        info = account.get("account_info") or {}
        base_url = str(account.get("site_url") or "").rstrip("/")
        name = safe_name(str(account.get("site_name") or base_url or account.get("id") or "unnamed"))

        if not ok:
            skipped.append(
                {
                    "name": name,
                    "base_url": base_url,
                    "site_type": account.get("site_type"),
                    "health": (account.get("health") or {}).get("status"),
                    "reasons": reasons,
                }
            )
            continue

        env_name = env_name_for(account)
        env_lines.append(f"{env_name}={shlex.quote(str(info.get('access_token')))}")
        entry = {
            "name": name,
            "type": "new-api",
            "base_url": base_url,
            "token_env": env_name,
            "user_id": str(info.get("id")) if info.get("id") is not None else None,
            "enabled": True,
            "source": "all-api-hub",
            "source_account_id": account.get("id"),
        }
        config_accounts.append(entry)
        imported.append({k: entry.get(k) for k in ("name", "base_url", "user_id", "source_account_id")})

    return {"accounts": config_accounts}, env_lines, {"imported_count": len(imported), "skipped_count": len(skipped), "imported": imported, "skipped": skipped}


def main() -> int:
    parser = argparse.ArgumentParser(description="Import All API Hub backup into api_hub_signin config")
    parser.add_argument("backup")
    parser.add_argument("--config-out", default="./api_hub_signin.json")
    parser.add_argument("--env-out", default="./api_hub_signin.env")
    parser.add_argument("--report-out", default="./api_hub_signin_import_report.json")
    args = parser.parse_args()

    config, env_lines, report = build_outputs(load_backup(args.backup))
    Path(args.config_out).write_text(json.dumps(config, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    Path(args.env_out).write_text("\n".join(env_lines) + "\n", encoding="utf-8")
    Path(args.report_out).write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.chmod(args.config_out, 0o600)
    os.chmod(args.env_out, 0o600)
    os.chmod(args.report_out, 0o600)

    print(f"imported={report['imported_count']} skipped={report['skipped_count']}")
    print(f"config={args.config_out}")
    print(f"env={args.env_out}")
    print(f"report={args.report_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
